'use client';
import { useEffect, useRef, useState } from 'react';
import { ArrowDown, ArrowLeft, ArrowRight, ArrowUpRight, Menu, Pause, Play, Volume2, VolumeX, X } from 'lucide-react';
import type { MediaItem } from '@/data/content';
import type { SiteConfig } from '@/data/site';
import { track } from '@/lib/analytics';
type Props={site:SiteConfig;gallery:MediaItem[]};
function Brand({compact=false}:{compact?:boolean}){return <a className={`brand ${compact?'brand--compact':''}`} href="#top" aria-label="DJ Sosô, voltar ao topo"><span>DJ</span><strong>SOSÔ</strong></a>}
function MediaPlaceholder({label,index=0,className=''}:{label:string;index?:number;className?:string}){return <figure className={`media-placeholder media-placeholder--${index%6} ${className}`} aria-label={`${label}, aguardando mídia oficial`}><span className="media-mark">SÔ</span><span className="media-label">{label}<small>MÍDIA OFICIAL EM BREVE</small></span></figure>}
const livePlayers:HTMLVideoElement[]=[];
let queueOn=false;
const pauseOthers=(keep:HTMLVideoElement)=>{for(const v of livePlayers)if(v!==keep&&!v.paused){try{v.pause()}catch{}}};
const pauseAll=()=>{queueOn=false;for(const v of livePlayers){try{v.pause()}catch{}}};
function VideoCard({item,index}:{item:MediaItem;index:number}){
  const ref=useRef<HTMLVideoElement>(null),controls=useRef<HTMLDivElement>(null),[active,setActive]=useState(false),[playing,setPlaying]=useState(false),[vol,setVol]=useState(1),[muted,setMuted]=useState(false),[time,setTime]=useState(0),[dur,setDur]=useState(0),[showVol,setShowVol]=useState(false);
  const autoPlay=async()=>{const v=ref.current;if(!v||!item.videoUrl||!v.paused)return;try{await v.play()}catch{if(!v.muted){v.muted=true;setMuted(true);try{await v.play()}catch{}}}};
  useEffect(()=>{const el=ref.current;if(!item.videoUrl||!el)return;const register=()=>{if(!livePlayers.includes(el))livePlayers.push(el)};const unregister=()=>{const i=livePlayers.indexOf(el);if(i>-1)livePlayers.splice(i,1)};register();const load=new IntersectionObserver(([e])=>setActive(e.isIntersecting),{rootMargin:'300px'});const out=new IntersectionObserver(([e])=>{if(!e.isIntersecting&&ref.current){ref.current.pause();setPlaying(false)}},{threshold:0.001});const focus=new IntersectionObserver(([e])=>{if(e.isIntersecting){if(queueOn)autoPlay()}else{const v=ref.current;if(v){v.pause();setPlaying(false)}}},{threshold:.5});load.observe(el);out.observe(el);focus.observe(el);return()=>{load.disconnect();out.disconnect();focus.disconnect();unregister()}},[item.videoUrl]);
  useEffect(()=>{const v=ref.current;if(v){v.volume=vol;v.muted=muted}},[vol,muted]);
  useEffect(()=>{if(!showVol)return;const close=(e:MouseEvent)=>{if(controls.current&&!controls.current.contains(e.target as Node))setShowVol(false)};document.addEventListener('mousedown',close);return()=>document.removeEventListener('mousedown',close)},[showVol]);
  const toggle=async()=>{const v=ref.current;if(!v||!item.videoUrl)return;if(v.paused){queueOn=true;try{await v.play();track('video_played',{id:item.id})}catch{}}else{v.pause();pauseAll();setPlaying(false)}};
  const changeVol=(v:number)=>{const el=ref.current;if(el){el.muted=v===0;el.volume=v;setMuted(v===0);setVol(v)}};
  const seek=(v:number)=>{const el=ref.current;if(el){el.currentTime=v;setTime(v)}};
  const toggleMute=()=>{const v=ref.current;if(!v)return;const m=!v.muted;v.muted=m;setMuted(m);if(!m)v.volume=vol||1};
 return <article className="gallery-slide gallery-slide--video"><div className="video-frame">{item.videoUrl?<video ref={ref} src={active?item.videoUrl:undefined} poster={item.poster} preload="none" playsInline onPlay={(e)=>{const el=e.currentTarget;if(!livePlayers.includes(el))livePlayers.push(el);pauseOthers(el);setPlaying(true)}} onPause={()=>setPlaying(false)} onEnded={()=>{setPlaying(false);track('video_completed',{id:item.id})}}/>:<MediaPlaceholder label="VÍDEO" index={index}/>}<span className="video-count">{String(index+1).padStart(2,'0')}</span><button className="play-button" onClick={toggle} aria-label={item.videoUrl?`${playing?'Pausar':'Reproduzir'} ${item.title??item.alt}`:`Mídia em breve para ${item.title??item.alt}`} disabled={!item.videoUrl}>{playing?<Pause/>:<Play fill="currentColor"/>}</button>{item.videoUrl&&<div className="video-controls"><button className="video-vol-btn" onClick={toggleMute} aria-label={muted?'Ativar som':'Silenciar'}>{muted||vol===0?<VolumeX/>:<Volume2/>}</button><input className="video-vol-slider" type="range" min="0" max="1" step="0.01" value={muted?0:vol} onChange={(e)=>changeVol(Number(e.target.value))} aria-label="Volume"/></div>}</div>{(item.title||item.subtitle)&&<div className="video-copy">{item.title&&<h3>{item.title}</h3>}{item.subtitle&&<p>{item.subtitle}</p>}</div>}</article>;
}
function GalleryCarousel({items,onOpenPhoto}:{items:MediaItem[];onOpenPhoto:(id:string)=>void}){
 const trackRef=useRef<HTMLDivElement>(null),[canPrev,setCanPrev]=useState(false),[canNext,setCanNext]=useState(true),[active,setActive]=useState(0);
 const step=()=>{const el=trackRef.current;if(!el)return 1;const first=el.firstElementChild as HTMLElement|null;return first?first.offsetWidth+14:el.clientWidth||1};
 const sync=()=>{const el=trackRef.current;if(!el)return;setCanPrev(el.scrollLeft>6);setCanNext(el.scrollLeft+el.clientWidth<el.scrollWidth-6);setActive(Math.round(el.scrollLeft/step()))};
 const scrollBy=(dir:number)=>{const el=trackRef.current;if(el)el.scrollBy({left:dir*step(),behavior:'smooth'})};
 const scrollTo=(i:number)=>{const el=trackRef.current;if(!el)return;const slides=Array.from(el.querySelectorAll<HTMLElement>('.gallery-slide'));if(slides[i])el.scrollTo({left:slides[i].offsetLeft,behavior:'smooth'})};
 useEffect(()=>{const el=trackRef.current;if(!el)return;const update=()=>{setCanPrev(el.scrollLeft>6);setCanNext(el.scrollLeft+el.clientWidth<el.scrollWidth-6);setActive(Math.round(el.scrollLeft/((el.firstElementChild as HTMLElement|null)?(el.firstElementChild as HTMLElement).offsetWidth+14:el.clientWidth||1)))};update();const ro=new ResizeObserver(update);ro.observe(el);window.addEventListener('resize',update);return()=>{ro.disconnect();window.removeEventListener('resize',update)}},[]);
 return <div className="gallery-carousel">
  <div className="gallery-track" ref={trackRef} onScroll={sync}>{items.map((item,g)=>item.type==='video'?<VideoCard key={item.id} item={item} index={g}/>:<figure key={item.id} className="gallery-slide gallery-slide--foto"><button className="gallery-photo" onClick={()=>onOpenPhoto(item.id)} aria-label={`Abrir ${item.alt}`}>{item.src?<img src={item.src} alt={item.alt} loading="lazy"/>:<MediaPlaceholder label="FOTO" index={g}/>}<span className="gallery-slide-index">{String(g+1).padStart(2,'0')}</span></button>{(item.title||item.subtitle)&&<figcaption className="video-copy">{item.title&&<h3>{item.title}</h3>}{item.subtitle&&<p>{item.subtitle}</p>}</figcaption>}</figure>)}</div>
  <button className="gallery-arrow gallery-arrow--prev" onClick={()=>scrollBy(-1)} disabled={!canPrev} aria-label="Anterior"><ArrowLeft/></button>
  <button className="gallery-arrow gallery-arrow--next" onClick={()=>scrollBy(1)} disabled={!canNext} aria-label="Próxima"><ArrowRight/></button>
  <div className="gallery-dots">{items.map((item,i)=><button key={item.id} className={`gallery-dot${i===active?' is-active':''}`} onClick={()=>scrollTo(i)} aria-label={`Ir para ${i+1}`}/>)}</div>
 </div>;
}
function Lightbox({items,index,onClose,onChange}:{items:MediaItem[];index:number;onClose:()=>void;onChange:(i:number)=>void}){
 const start=useRef(0);useEffect(()=>{const key=(e:KeyboardEvent)=>{if(e.key==='Escape')onClose();if(e.key==='ArrowRight')onChange((index+1)%items.length);if(e.key==='ArrowLeft')onChange((index-1+items.length)%items.length)};window.addEventListener('keydown',key);document.body.style.overflow='hidden';return()=>{window.removeEventListener('keydown',key);document.body.style.overflow=''}},[index,items.length,onChange,onClose]);const item=items[index];
 return <dialog open className="lightbox" aria-label="Visualizador de imagens da galeria" onTouchStart={e=>start.current=e.touches[0].clientX} onTouchEnd={e=>{const dx=e.changedTouches[0].clientX-start.current;if(Math.abs(dx)>45)onChange((index+(dx<0?1:-1)+items.length)%items.length)}}><button className="lightbox-close" onClick={onClose} aria-label="Fechar galeria"><X/></button><button className="lightbox-prev" onClick={()=>onChange((index-1+items.length)%items.length)} aria-label="Imagem anterior"><ArrowLeft/></button><div className="lightbox-media">{item.src?<img src={item.src} alt={item.alt} className="lightbox-img"/>:<MediaPlaceholder label="FOTO" index={index}/>}<p>{String(index+1).padStart(2,'0')} / {items.length}</p></div><button className="lightbox-next" onClick={()=>onChange((index+1)%items.length)} aria-label="Próxima imagem"><ArrowRight/></button></dialog>;
}
export function WhatsAppGlyph({w=20}:{w?:number}){return <svg width={w} height={w} viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><path d="M20.52 3.449A11.945 11.945 0 0 0 12.105 0C5.507 0 .16 5.335.157 11.892c0 2.096.547 4.142 1.588 5.945L.057 24l6.305-1.654a11.882 11.882 0 0 0 5.683 1.448h.005c6.554 0 11.89-5.335 11.893-11.893a11.821 11.821 0 0 0-3.48-8.413ZM12.12 21.764h-.004a9.87 9.87 0 0 1-5.031-1.378l-.361-.214-3.741.982.998-3.648-.235-.374a9.86 9.86 0 0 1-1.51-5.26c.001-5.45 4.436-9.884 9.888-9.884 2.64 0 5.122 1.03 6.988 2.898a9.825 9.825 0 0 1 2.893 6.994c-.003 5.45-4.437 9.884-9.885 9.884m8.413-18.297A11.815 11.815 0 0 0 12.05 0C5.495 0 .16 5.335.157 11.892c0 2.096.547 4.142 1.588 5.945L.057 24l6.305-1.654a11.882 11.882 0 0 0 5.683 1.448h.005c6.554 0 11.89-5.335 11.893-11.893a11.821 11.821 0 0 0-3.48-8.413Z"/></svg>}

export function SiteExperience({site,gallery}:Props){const[menu,setMenu]=useState(false),[lightbox,setLightbox]=useState<number|null>(null),[fab,setFab]=useState(false);useEffect(()=>{const onScroll=()=>{const r=document.getElementById('contact')?.getBoundingClientRect();setFab(window.scrollY>window.innerHeight*.6&&(r?r.top>window.innerHeight*.7:true))};onScroll();window.addEventListener('scroll',onScroll,{passive:true});return()=>window.removeEventListener('scroll',onScroll)},[]);const photos=gallery.filter(m=>m.type==='foto');const photoIndex=new Map(photos.map((p,i)=>[p.id,i]));return <main id="top">
 <header className="header"><Brand compact/><nav className="desktop-nav" aria-label="Navegação principal">{site.navigation.map(i=><a key={i.href} href={i.href}>{i.label}</a>)}</nav><button className="menu-button" onClick={()=>setMenu(true)} aria-label="Abrir menu"><span>MENU</span><Menu/></button></header>
 {menu&&<div className="mobile-menu"><button onClick={()=>setMenu(false)} aria-label="Fechar menu"><X/></button><Brand/><nav>{site.navigation.map((i,n)=><a key={i.href} href={i.href} onClick={()=>setMenu(false)}><span>0{n+1}</span>{i.label}</a>)}</nav><p>{site.location}</p></div>}
 <section className="hero"><div className="hero-media"><img src="/dj-soso-hero.webp" alt="DJ Sosô usando fones de ouvido e jaqueta dourada" width="1024" height="1536" fetchPriority="high" /><div className="hero-stamp"><b>9</b><span>ANOS</span></div></div><div className="hero-kicker"><span>SP / BR</span></div><div className="hero-bottom"><p>9 anos.<br/>A nova geração<br/>que vai comandar as pistas.</p><p className="hero-sub">Sofia integra um seleto grupo de meninas brasileiras que chega à música cedo, pronta para fazer história ainda na infância.</p><div className="hero-actions"><a className="button button--light" href="#gallery" onClick={()=>track('hero_watch_clicked')}>VEJA SOSÔ TOCAR <Play/></a><a className="text-link" href="#contact">CONTATO <ArrowDown/></a></div></div></section>
 <section className="about section" id="about"><div className="section-index">01 / SOBRE</div><div className="about-title"><p>ESTA É</p><h2>SOSÔ</h2></div><figure className="about-media"><img src="/dj-soso-bio.webp" alt="DJ Sosô usando fones de ouvido e fazendo uma bolha de chiclete" width="1024" height="1536" loading="lazy" /></figure><div className="about-copy"><p className="lead">Sofia tem 9 anos.</p><p>A música começou como brincadeira.</p><p>Hoje ela está aprendendo como as músicas são construídas: mixagem, teclados, sintetizadores, loops, vocais, Ableton e tudo que puder colocar as mãos.</p><p>Ela ainda está no começo.</p><p className="accent-copy">E essa é exatamente a parte divertida.</p></div><div className="about-stamp">CURIOSA<br/>POR NATUREZA</div></section>
 <section className="gallery section" id="gallery"><div className="section-index">02 / GALERIA</div><div className="gallery-heading"><h2>GALERIA</h2></div>{gallery.length>0?<GalleryCarousel items={gallery} onOpenPhoto={(id)=>setLightbox(photoIndex.get(id)??0)}/>:null}</section>
 <section className="equip section" id="equipamentos"><div className="section-index">03 / EQUIPAMENTOS</div><div className="equip-title"><p>LOCAÇÃO DE</p><h2>EQUIPAMENTOS</h2></div><p className="equip-lead">Quer montar a estrutura do seu evento? A Sosô também fornece áudio e captura, com operação pela própria equipe.</p><div className="lease-grid"><div className="lease-col"><div className="lease-head">ÁUDIO &amp; PERFORMANCE</div><ul>{site.gear.audio.map(g=><li key={g}>{g}</li>)}</ul></div><div className="lease-col"><div className="lease-head">CAPTURA</div><ul>{site.gear.capture.map(g=><li key={g}>{g}</li>)}</ul></div></div><p className="equip-note">Locação avulsa ou incluída na contratação da DJ. Chame a gestão para montar a proposta.</p><a className="whatsapp-button" href={site.contact.whatsapp} onClick={()=>track('whatsapp_clicked')}>ORÇAR ESTRUTURA <ArrowUpRight/></a><div className="coverage"><span>COBERTURA FOTOGRÁFICA DO EVENTO</span><div className="coverage-item"><b>SHOW + EVENTO</b><p>Além do show, uma equipe de audiovisual profissional, com experiência em grandes eventos nacionais e internacionais, cobre o evento por inteiro.</p></div><div className="coverage-item"><b>DURAÇÃO A NEGOCIAR</b><p>Pacotes de 4h, 8h ou mais. Garantimos o registro do show e também o da festa.</p></div></div></section>
 <section className="booking section" id="contact"><div className="section-index">04 / CONTATO</div><div className="booking-title"><p>TOQUE COM</p><h2>SOSÔ</h2></div><div className="booking-copy"><p className="lead">Quer que a DJ Sosô toque no seu espaço ou evento?</p><div className="sheet"><div className="sheet-row rep"><span>REPERTÓRIO</span><ul>{site.repertoire.map(r=><li key={r}>{r}</li>)}</ul></div><div className="sheet-row"><span>BASE</span><p>{site.location}, com alcance nacional e internacional</p></div></div><div className="manager"><span>AGENDA &amp; GESTÃO</span><strong>{site.contact.manager}</strong><p>{site.contact.role}</p></div><div className="booking-actions booking-actions--center"><a className="whatsapp-button" href={site.contact.whatsapp} onClick={()=>track('whatsapp_clicked')}>WHATSAPP <ArrowUpRight/></a></div><small>Toda comunicação é feita por um adulto responsável.</small><div className="custom-set"><span>SETS PERSONALIZADOS</span><p>Quer um set feito com as músicas que você escolher? Possível, mas exige estudo. Combine com no mínimo 7 dias corridos de antecedência.</p></div><div className="coverage"><span>COBERTURA &amp; PRAZOS</span><div className="coverage-item"><b>200 KM POR TERRA</b><p>Agenda normal em São Paulo, capital e região.</p></div><div className="coverage-item"><b>GRANDES DISTÂNCIAS</b><p>Em viagem aérea, somente durante as férias escolares. Quanto maior a distância, maior a antecedência.</p></div></div></div></section>
 <footer><Brand/><div className="footer-contact"><p>{site.location}</p><p>AGENDA &amp; GESTÃO<br/>{site.contact.manager}</p><a href={`mailto:${site.contact.email}`}>{site.contact.email}</a><a href={site.contact.whatsapp} onClick={()=>track('whatsapp_clicked')}>WHATSAPP <ArrowUpRight/></a></div><div className="footer-social">{(['instagram','tiktok'] as const).map(n=><a key={n} href={site.social[n]} onClick={()=>track(`${n}_clicked`)}>{n.toUpperCase()} <ArrowUpRight/></a>)}</div><p className="copyright">© {new Date().getFullYear()} DJ SOSÔ</p></footer><a className={`whatsapp-fab${fab?' is-visible':''}`} href={site.contact.whatsapp} onClick={()=>track('whatsapp_fab_clicked')} aria-label="Chamar a DJ Sosô no WhatsApp"><svg viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><path d="M17.472 14.382c-.297-.149-1.758-.867-2.03-.967-.273-.099-.471-.148-.67.15-.197.297-.767.966-.94 1.164-.173.199-.347.223-.644.075-.297-.15-1.255-.463-2.39-1.475-.883-.788-1.48-1.761-1.653-2.059-.173-.297-.018-.458.13-.606.134-.133.298-.347.446-.52.149-.174.198-.298.298-.497.099-.198.05-.371-.025-.52-.075-.149-.669-1.612-.916-2.207-.242-.579-.487-.5-.669-.51-.173-.008-.371-.01-.57-.01-.198 0-.52.074-.792.372-.272.297-1.04 1.016-1.04 2.479 0 1.462 1.065 2.875 1.213 3.074.149.198 2.096 3.2 5.077 4.487.709.306 1.262.489 1.694.625.712.227 1.36.195 1.871.118.571-.085 1.758-.719 2.006-1.413.248-.694.248-1.289.173-1.413-.074-.124-.272-.198-.57-.347m-5.421 7.403h-.004a9.87 9.87 0 0 1-5.031-1.378l-.361-.214-3.741.982.998-3.648-.235-.374a9.86 9.86 0 0 1-1.51-5.26c.001-5.45 4.436-9.884 9.888-9.884 2.64 0 5.122 1.03 6.988 2.898a9.825 9.825 0 0 1 2.893 6.994c-.003 5.45-4.437 9.884-9.885 9.884m8.413-18.297A11.815 11.815 0 0 0 12.05 0C5.495 0 .16 5.335.157 11.892c0 2.096.547 4.142 1.588 5.945L.057 24l6.305-1.654a11.882 11.882 0 0 0 5.683 1.448h.005c6.554 0 11.89-5.335 11.893-11.893a11.821 11.821 0 0 0-3.48-8.413Z"/></svg><span>WHATSAPP</span></a>{lightbox!==null&&photos.length>0&&<Lightbox items={photos} index={lightbox} onClose={()=>setLightbox(null)} onChange={setLightbox}/>}</main>}