'use client';
import { useEffect, useRef, useState } from 'react';
import { ArrowDown, ArrowLeft, ArrowRight, ArrowUpRight, Menu, Pause, Play, Volume2, X } from 'lucide-react';
import type { MediaItem, VideoItem } from '@/data/content';
import type { SiteConfig } from '@/data/site';
import { track } from '@/lib/analytics';
type Props={site:SiteConfig;videos:VideoItem[];musicLab:{id:string;title:string;copy:string;index:number}[];story:{id:string;lines:string[];note:string}[];gallery:MediaItem[]};
function Brand({compact=false}:{compact?:boolean}){return <a className={`brand ${compact?'brand--compact':''}`} href="#top" aria-label="DJ Sosô, back to top"><span>DJ</span><strong>SOSÔ</strong></a>}
function MediaPlaceholder({label,index=0,className=''}:{label:string;index?:number;className?:string}){return <figure className={`media-placeholder media-placeholder--${index%6} ${className}`} aria-label={`${label} — placeholder awaiting official media`}><span className="media-mark">SÔ</span><span className="media-label">{label}<small>OFFICIAL MEDIA COMING SOON</small></span></figure>}
function VideoCard({video,index}:{video:VideoItem;index:number}){
 const ref=useRef<HTMLVideoElement>(null),[active,setActive]=useState(false),[playing,setPlaying]=useState(false);
 useEffect(()=>{if(!video.videoUrl||!ref.current)return;const ob=new IntersectionObserver(([e])=>setActive(e.isIntersecting),{rootMargin:'300px'});ob.observe(ref.current);return()=>ob.disconnect()},[video.videoUrl]);
 const toggle=async()=>{if(!video.videoUrl||!ref.current)return;if(playing)ref.current.pause();else{await ref.current.play();track('video_played',{id:video.id})}};
 return <article className="video-card"><div className="video-frame">{video.source==='direct'&&video.videoUrl?<video ref={ref} src={active?video.videoUrl:undefined} poster={video.poster} preload="none" playsInline muted onPlay={()=>setPlaying(true)} onPause={()=>setPlaying(false)} onEnded={()=>{setPlaying(false);track('video_completed',{id:video.id})}}/>:<MediaPlaceholder label={video.category} index={index}/>}<span className="video-count">0{index+1}</span><button className="play-button" onClick={toggle} aria-label={video.videoUrl?`${playing?'Pause':'Play'} ${video.title}`:`Media placeholder for ${video.title}`} disabled={!video.videoUrl}>{playing?<Pause/>:<Play fill="currentColor"/>}</button><span className="sound-note"><Volume2/> SOUND NEVER AUTOPLAYS</span></div><div className="video-copy"><p className="eyebrow">{video.category}</p><h3>{video.title}</h3><p>{video.subtitle}</p></div></article>
}
function Lightbox({items,index,onClose,onChange}:{items:MediaItem[];index:number;onClose:()=>void;onChange:(i:number)=>void}){
 const start=useRef(0);useEffect(()=>{const key=(e:KeyboardEvent)=>{if(e.key==='Escape')onClose();if(e.key==='ArrowRight')onChange((index+1)%items.length);if(e.key==='ArrowLeft')onChange((index-1+items.length)%items.length)};window.addEventListener('keydown',key);document.body.style.overflow='hidden';return()=>{window.removeEventListener('keydown',key);document.body.style.overflow=''}},[index,items.length,onChange,onClose]);const item=items[index];
 return <dialog open className="lightbox" aria-label="Gallery image viewer" onTouchStart={e=>start.current=e.touches[0].clientX} onTouchEnd={e=>{const dx=e.changedTouches[0].clientX-start.current;if(Math.abs(dx)>45)onChange((index+(dx<0?1:-1)+items.length)%items.length)}}><button className="lightbox-close" onClick={onClose} aria-label="Close gallery"><X/></button><button className="lightbox-prev" onClick={()=>onChange((index-1+items.length)%items.length)} aria-label="Previous image"><ArrowLeft/></button><div className="lightbox-media"><MediaPlaceholder label={item.category.toUpperCase()} index={index}/><p>{String(index+1).padStart(2,'0')} / {items.length}</p></div><button className="lightbox-next" onClick={()=>onChange((index+1)%items.length)} aria-label="Next image"><ArrowRight/></button></dialog>
}
export function SiteExperience({site,videos,musicLab,story,gallery}:Props){const[menu,setMenu]=useState(false),[lightbox,setLightbox]=useState<number|null>(null);return <main id="top">
 <header className="header"><Brand compact/><nav className="desktop-nav" aria-label="Main navigation">{site.navigation.map(i=><a key={i.href} href={i.href}>{i.label}</a>)}</nav><button className="menu-button" onClick={()=>setMenu(true)} aria-label="Open menu"><span>MENU</span><Menu/></button></header>
 {menu&&<div className="mobile-menu"><button onClick={()=>setMenu(false)} aria-label="Close menu"><X/></button><Brand/><nav>{site.navigation.map((i,n)=><a key={i.href} href={i.href} onClick={()=>setMenu(false)}><span>0{n+1}</span>{i.label}</a>)}</nav><p>{site.location}</p></div>}
 <section className="hero" aria-labelledby="hero-title"><div className="hero-media"><MediaPlaceholder label="PORTRAIT" index={1}/></div><div className="hero-kicker"><span>09 YEARS OLD</span><span>SP / BR</span></div><h1 id="hero-title"><span>DJ</span><strong>SOSÔ</strong></h1><div className="hero-bottom"><p>9 years old.<br/>Just getting started.</p><div className="hero-actions"><a className="button button--light" href="#watch" onClick={()=>track('hero_watch_clicked')}>WATCH SOSÔ PLAY <Play/></a><a className="text-link" href="#contact">CONTACT <ArrowDown/></a></div></div></section>
 <section className="about section" id="about"><div className="section-index">01 / ABOUT</div><div className="about-title"><p>THIS IS</p><h2>SOSÔ</h2></div><div className="about-copy"><p className="lead">Sofia is 9.</p><p>Music started as play.</p><p>Today she&apos;s learning how tracks are built — mixing, keyboards, synths, loops, vocals, Ableton and everything she can get her hands on.</p><p>She&apos;s still at the beginning.</p><p className="accent-copy">And that&apos;s exactly the fun part.</p></div><div className="about-stamp">CURIOUS<br/>BY NATURE</div></section>
 <section className="watch section" id="watch"><div className="section-index">02 / WATCH</div><div className="section-heading"><h2>WATCH HER<br/><em>PLAY</em></h2><p>Not a showreel. A work in progress — one transition, melody and loop at a time.</p></div><div className="video-list">{videos.map((v,i)=><VideoCard key={v.id} video={v} index={i}/>)}</div></section>
 <section className="lab section" id="music-lab"><div className="section-index">03 / MUSIC LAB</div><div className="lab-heading"><h2>SOSÔ&apos;S<br/><span>MUSIC LAB</span></h2><p>Touch, listen, repeat. This is where curiosity becomes sound.</p></div><div className="lab-grid">{musicLab.map(i=><article key={i.id} className="lab-card"><span>0{i.index+1}</span><div className="lab-wave" aria-hidden="true">{[1,2,3,4,5,6,7,8].map(n=><i key={n}/>)}</div><h3>{i.title}</h3><p>{i.copy}</p><ArrowUpRight/></article>)}</div></section>
 <section className="story section"><div className="section-index">04 / STORY</div><div className="story-list">{story.map((item,i)=><article key={item.id} className="story-beat"><p>{item.note}</p><h2>{item.lines.map(line=><span key={line}>{line}</span>)}</h2>{i<story.length-1&&<div className="story-media"><MediaPlaceholder label={item.id.toUpperCase()} index={i+2}/></div>}</article>)}</div></section>
 <section className="gallery section" id="gallery"><div className="section-index">05 / GALLERY</div><div className="gallery-heading"><h2>GALLERY</h2><p>Portraits, equipment, practice and everything in between.</p></div><div className="gallery-grid">{gallery.map((item,i)=><button key={item.id} className={`gallery-item gallery-item--${i%5}`} onClick={()=>{setLightbox(i);track('gallery_opened',{id:item.id})}} aria-label={`Open ${item.alt}`}><MediaPlaceholder label={item.category.toUpperCase()} index={i}/><span>{String(i+1).padStart(2,'0')}</span></button>)}</div></section>
 <section className="social section"><div className="section-index">06 / SOCIAL</div><h2>FOLLOW<br/><em>THE NOISE</em></h2><div className="social-links">{(['instagram','tiktok','youtube'] as const).map(n=><a key={n} href={site.social[n]} onClick={()=>track(`${n}_clicked`)}>{n.toUpperCase()} <ArrowUpRight/></a>)}</div></section>
 <section className="booking section" id="contact"><div className="section-index">07 / CONTACT</div><div className="booking-title"><p>PLAY WITH</p><h2>SOSÔ</h2></div><div className="booking-copy"><p className="lead">Interested in having DJ Sosô play at your venue or event?</p><div className="manager"><span>BOOKING &amp; MANAGEMENT</span><strong>{site.contact.manager}</strong><p>{site.contact.role}</p></div><div className="booking-actions"><a className="button button--dark" href={`mailto:${site.contact.email}`} onClick={()=>track('booking_contact_clicked')}>CONTACT MANAGEMENT <ArrowUpRight/></a><a className="text-link dark" href={site.contact.whatsapp} onClick={()=>track('whatsapp_clicked')}>WHATSAPP <ArrowUpRight/></a></div><small>All communication is handled by a responsible adult.</small></div></section>
 <footer><Brand/><div><p>{site.location}</p><p>BOOKING &amp; MANAGEMENT<br/>{site.contact.manager}</p></div><div>{(['instagram','tiktok','youtube'] as const).map(n=><a key={n} href={site.social[n]}>{n.toUpperCase()} ↗</a>)}</div><p className="copyright">© {new Date().getFullYear()} DJ SOSÔ</p></footer>{lightbox!==null&&<Lightbox items={gallery} index={lightbox} onClose={()=>setLightbox(null)} onChange={setLightbox}/>}</main>}
